# Code copied by https://geshan.com.np/blog/2023/01/nextjs-docker/

version: '3.8'
services:
  web:
    container_name: 'database-training-web'
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
